javascripts:
  - 'https://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js'
  - 'rails' # For UJS
  - 'jquery.ezCookie_0.7.01' # For subcookie magic. See http://code.google.com/p/ezcookie/
  - 'configatron'
  - 'application' # This should be last

api:
  key: 'b39ee8d5f05d0f566a0080b4c310ceddf5dc5f7606a616f53'
  base_path: 'http://beta.wordnik.com/api/'

# synonym, antonym, form, hyponym, variant, verb-stem, verb-form, cross-reference, same-context  
desirable_relation_types:
  - 'antonym'
  - 'same-context'
  - 'equivalent'
  - 'synonym'
mode_keys:
  - 'antonymy'
  - 'synonymy'
  - 'rhyme'
  - 'free_association'
modes:
  antonymy: "is the opposite of"
  synonymy: "is another word for"
  rhyme: "rhymes with"
  free_association: "makes me think of"