development:
  adapter: mysql2
  database: word_pong_development
  username: root
  encoding: utf8

test:
  adapter: mysql2
  database: word_pong_test
  username: root
  encoding: utf8

cucumber:
  <<: *test